<?php

use Illuminate\Database\Seeder;

class CityTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      $data = array(
      ['id' => 1, 'state_id' => 1, 'name' => 'Port Blair'],
      ['id' => 2, 'state_id' => 1, 'name' => 'Garacharma'],
      ['id' => 3, 'state_id' => 2, 'name' => 'Vijayawada'],
      ['id' => 4, 'state_id' => 2, 'name' => 'Visakhapatnam'],
      ['id' => 5, 'state_id' => 3, 'name' => 'Tawang'],
      ['id' => 6, 'state_id' => 3, 'name' => 'Itanagar'],
      ['id' => 7, 'state_id' => 4, 'name' => 'Guwahati'],
      ['id' => 8, 'state_id' => 4, 'name' => 'Jorhat'],
      ['id' => 9, 'state_id' => 5, 'name' => 'Patna'],
      ['id' => 10, 'state_id' => 5, 'name' => 'Gaya'],
      ['id' => 11, 'state_id' => 6, 'name' => 'Udhampur'],
      ['id' => 12, 'state_id' => 6, 'name' => 'Bathinda'],
      ['id' => 13, 'state_id' => 7, 'name' => 'Raipur'],
      ['id' => 14, 'state_id' => 7, 'name' => 'Bilaspur'],      
      ['id' => 15, 'state_id' => 8, 'name' => 'Silvassa'],
      ['id' => 16, 'state_id' => 8, 'name' => 'Vapi'],     
      ['id' => 17, 'state_id' => 9, 'name' => 'Diu'],
      ['id' => 18, 'state_id' => 9, 'name' => 'Daman'],     
      ['id' => 19, 'state_id' => 10, 'name' => 'New Delhi'],
      ['id' => 20, 'state_id' => 10, 'name' => 'Gurugram'],  
      ['id' => 21, 'state_id' => 11, 'name' => 'Panaji'],
      ['id' => 22, 'state_id' => 11, 'name' => 'Mapusa'],
      ['id' => 23, 'state_id' => 12, 'name' => 'Panchmahal'],
      ['id' => 24, 'state_id' => 12, 'name' => 'Kutch'],
      ['id' => 25, 'state_id' => 13, 'name' => 'Faridabad'],
      ['id' => 26, 'state_id' => 13, 'name' => 'Gurgaon'],
      ['id' => 27, 'state_id' => 14, 'name' => 'Shimla'],
      ['id' => 28, 'state_id' => 14, 'name' => 'Mandi'],
      ['id' => 29, 'state_id' => 15, 'name' => 'Jammu'],
      ['id' => 30, 'state_id' => 15, 'name' => 'Srinagar'],
      ['id' => 31, 'state_id' => 16, 'name' => 'Ranchi'],
      ['id' => 32, 'state_id' => 16, 'name' => 'Dhanbad'],
      ['id' => 33, 'state_id' => 17, 'name' => 'Bengaluru'],
      ['id' => 34, 'state_id' => 17, 'name' => 'Manglore'],
      ['id' => 35, 'state_id' => 18, 'name' => 'Thiruvananthapuram'],
      ['id' => 36, 'state_id' => 18, 'name' => 'Kochi'],
      ['id' => 37, 'state_id' => 19, 'name' => 'Kavaratti'],
      ['id' => 38, 'state_id' => 19, 'name' => 'Minicoy'],
      ['id' => 39, 'state_id' => 20, 'name' => 'Bhopal'],
      ['id' => 40, 'state_id' => 20, 'name' => 'Indore'],
      ['id' => 41, 'state_id' => 21, 'name' => 'Mumbai'],
      ['id' => 42, 'state_id' => 21, 'name' => 'Pune'],
      ['id' => 43, 'state_id' => 21, 'name' => 'Ratnagiri'],
      ['id' => 44, 'state_id' => 22, 'name' => 'Imphal'],
      ['id' => 45, 'state_id' => 22, 'name' => 'Kakching'],
      ['id' => 46, 'state_id' => 23, 'name' => 'Shillong'],
      ['id' => 47, 'state_id' => 23, 'name' => 'Mairang'],
      ['id' => 48, 'state_id' => 24, 'name' => 'Aizawl'],
      ['id' => 49, 'state_id' => 24, 'name' => 'Saitual'],
      ['id' => 50, 'state_id' => 25, 'name' => 'Kohima'],
      ['id' => 51, 'state_id' => 25, 'name' => 'Dimapur'],
      ['id' => 52, 'state_id' => 26, 'name' => 'Bhubaneshwar'],
      ['id' => 53, 'state_id' => 26, 'name' => 'Rourkela'],
      ['id' => 54, 'state_id' => 27, 'name' => 'Puducherry'],
      ['id' => 55, 'state_id' => 27, 'name' => 'Karaikal'],
      ['id' => 56, 'state_id' => 28, 'name' => 'Jalandhar'],
      ['id' => 57, 'state_id' => 28, 'name' => 'Amritsar'],
      ['id' => 58, 'state_id' => 29, 'name' => 'Jaipur'],
      ['id' => 59, 'state_id' => 29, 'name' => 'Kota'],
      ['id' => 60, 'state_id' => 30, 'name' => 'Gangtok'],
      ['id' => 61, 'state_id' => 30, 'name' => 'Namchi'],
      ['id' => 62, 'state_id' => 31, 'name' => 'Chennai'],
      ['id' => 63, 'state_id' => 32, 'name' => 'Hyderabad'],
      ['id' => 64, 'state_id' => 33, 'name' => 'Agartala'],
      ['id' => 65, 'state_id' => 34, 'name' => 'Kanpur'],
      ['id' => 66, 'state_id' => 35, 'name' => 'Rudrapur'],
      ['id' => 67, 'state_id' => 36, 'name' => 'Kolkata'],
      ['id' => 68, 'state_id' => 34, 'name' => 'Agra'],
      ['id' => 69, 'state_id' => 19, 'name' => 'Agatti'],
      ['id' => 70, 'state_id' => 12, 'name' => 'Ahmedabad'],
      ['id' => 71, 'state_id' => 12, 'name' => 'Vadodara'],
      ['id' => 72, 'state_id' => 20, 'name' => 'Bareli'],
      ['id' => 73, 'state_id' => 17, 'name' => 'Bellary'],
      ['id' => 74, 'state_id' => 12, 'name' => 'Bhuj'],
      ['id' => 75, 'state_id' => 13, 'name' => 'Bhavnagar'],
      ['id' => 76, 'state_id' => 29, 'name' => 'Bikaner'],
      ['id' => 77, 'state_id' => 28, 'name' => 'Bhatinda'],
      ['id' => 78, 'state_id' => 1, 'name' => 'Car Nicobar'],
      ['id' => 79, 'state_id' => 18, 'name' => 'Calicut'],
      ['id' => 80, 'state_id' => 2, 'name' => 'Cuddapah'],
      ['id' => 81, 'state_id' => 31, 'name' => 'Coimbatore'],
      ['id' => 82, 'state_id' => 36, 'name' => 'Cooch Behar'],
      ['id' => 83, 'state_id' => 35, 'name' => 'Dehradun'],
      ['id' => 84, 'state_id' => 14, 'name' => 'Dharamsala'],
      ['id' => 85, 'state_id' => 4, 'name' => 'Dibrugarh'],
      ['id' => 86, 'state_id' => 11, 'name' => 'Dabolim'],
      ['id' => 87, 'state_id' => 34, 'name' => 'Gorakhpur'],
      ['id' => 88, 'state_id' => 20, 'name' => 'Guna'],
      ['id' => 89, 'state_id' => 20, 'name' => 'Gwalior'],
      ['id' => 90, 'state_id' => 17, 'name' => 'Hubli'],
      ['id' => 91, 'state_id' => 20, 'name' => 'Khajuraho'],
      ['id' => 92, 'state_id' => 13, 'name' => 'Hissar'],
      ['id' => 93, 'state_id' => 21, 'name' => 'Nashik'],
      ['id' => 94, 'state_id' => 33, 'name' => 'Singerbhil'],
      ['id' => 95, 'state_id' => 36, 'name' => 'Bagdogra'],
      ['id' => 96, 'state_id' => 28, 'name' => 'Chandigarh'],
      ['id' => 97, 'state_id' => 34, 'name' => 'Bamrauli'],
      ['id' => 98, 'state_id' => 17, 'name' => 'Bajpe'],
      ['id' => 99, 'state_id' => 17, 'name' => 'Sambre'],
      ['id' => 100, 'state_id' => 33, 'name' => 'Kailashahar'],
      ['id' => 101, 'state_id' => 4, 'name' => 'North Lakhimpur'],
      ['id' => 102, 'state_id' => 15, 'name' => 'Satwari'],
      ['id' => 103, 'state_id' => 12, 'name' => 'Keshod'],
      ['id' => 104, 'state_id' => 15, 'name' => 'Bakula Rimpoche'],
      ['id' => 105, 'state_id' => 31, 'name' => 'Madurai'],
      ['id' => 106, 'state_id' => 33, 'name' => 'Khowai'],
      ['id' => 107, 'state_id' => 28, 'name' => 'Pathankot'],
      ['id' => 108, 'state_id' => 33, 'name' => 'Kamalpur'],
      ['id' => 109, 'state_id' => 4, 'name' => 'Kumbhirgram'],
      ['id' => 110, 'state_id' => 3, 'name' => 'Pasighat'],
      ['id' => 111, 'state_id' => 21, 'name' => 'Aurangabad'],
      ['id' => 112, 'state_id' => 3, 'name' => 'Along'],
      ['id' => 113, 'state_id' => 16, 'name' => 'Jamshedpur'],
      ['id' => 114, 'state_id' => 12, 'name' => 'Gandhidham'],
      ['id' => 115, 'state_id' => 29, 'name' => 'Jodhpur'],
      ['id' => 116, 'state_id' => 12, 'name' => 'Jamnagar'],
      ['id' => 117, 'state_id' => 7, 'name' => 'Jagdalpur'],
      ['id' => 118, 'state_id' => 20, 'name' => 'Jabalpur'],
      ['id' => 119, 'state_id' => 29, 'name' => 'Jaisalmer'],
      ['id' => 120, 'state_id' => 21, 'name' => 'Kolhapur'],
      ['id' => 121, 'state_id' => 14, 'name' => 'Kullu'],
      ['id' => 122, 'state_id' => 36, 'name' => 'Malda'],
      ['id' => 123, 'state_id' => 34, 'name' => 'Lucknow'],
      ['id' => 124, 'state_id' => 21, 'name' => 'Latur'],
      ['id' => 125, 'state_id' => 28, 'name' => 'Ludhiana'],
      ['id' => 126, 'state_id' => 17, 'name' => 'Mysore'],
      ['id' => 127, 'state_id' => 5, 'name' => 'Muzaffarpur'],
      ['id' => 128, 'state_id' => 21, 'name' => 'Nagpur'],
      ['id' => 129, 'state_id' => 21, 'name' => 'Nanded'],
      ['id' => 130, 'state_id' => 31, 'name' => 'Neyveli'],
      ['id' => 131, 'state_id' => 12, 'name' => 'Porbandar'],
      ['id' => 132, 'state_id' => 35, 'name' => 'Pantnagar'],
      ['id' => 133, 'state_id' => 2, 'name' => 'Puttaprathe'],
      ['id' => 134, 'state_id' => 26, 'name' => 'Jeypore'],
      ['id' => 135, 'state_id' => 12, 'name' => 'Gandhigram'],
      ['id' => 136, 'state_id' => 20, 'name' => 'Rewa'],
      ['id' => 137, 'state_id' => 36, 'name' => 'Balurghat'],
      ['id' => 138, 'state_id' => 2, 'name' => 'Madhurapudi'],
      ['id' => 139, 'state_id' => 15, 'name' => 'Rajouri'],
      ['id' => 140, 'state_id' => 32, 'name' => 'Ramagundam'],
      ['id' => 141, 'state_id' => 4, 'name' => 'Rupsi'],
      ['id' => 142, 'state_id' => 23, 'name' => 'Umroi'],
      ['id' => 143, 'state_id' => 14, 'name' => 'Jubbarhatti'],
      ['id' => 144, 'state_id' => 21, 'name' => 'Sholapur'],
      ['id' => 145, 'state_id' => 12, 'name' => 'Surat'],
      ['id' => 146, 'state_id' => 31, 'name' => 'Salem'],
      ['id' => 147, 'state_id' => 31, 'name' => 'Tuticorin'],
      ['id' => 148, 'state_id' => 3, 'name' => 'Tezu'],
      ['id' => 149, 'state_id' => 4, 'name' => 'Tezpur'],
      ['id' => 150, 'state_id' => 2, 'name' => 'Tirupati'],
      ['id' => 151, 'state_id' => 31, 'name' => 'Thanjavur'],
      ['id' => 152, 'state_id' => 20, 'name' => 'Satna'],
      ['id' => 153, 'state_id' => 31, 'name' => 'Tiruchirappalli'],
      ['id' => 154, 'state_id' => 29, 'name' => 'Udaipur'],
      ['id' => 155, 'state_id' => 17, 'name' => 'Toranagallu'],
      ['id' => 156, 'state_id' => 34, 'name' => 'Babatpur'],
      ['id' => 157, 'state_id' => 32, 'name' => 'Warangal'],
      ['id' => 158, 'state_id' => 3, 'name' => 'Ziro'],);
      DB::table('city')->insert($data);
    }
}
